### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by gopi77** [yihui-he/u-net#7] opened 2017-09-18 12:25 UTC
Hi

I followed the steps.

1. python data.py generated 4 files (imgs_train.npy, imgs_mask_train.npy, imgs_test.npy & imgs_id_test.npy)
2. python train.py gave below error. ( [train.py.tar.gz](https://github.com/yihui-he/u-net/files/1310618/train.py.tar.gz) )

>>>>>>>>>>>>>>>>>>

```
Using TensorFlow backend.
------------------------------
Loading and preprocessing train data...
------------------------------
(array([ 1128086, 18525490, 48198109, 50544455, 31160281, 21835121,
       14112760,  6650318,  4792944,  5010836]), array([ -23.21516418,    7.21833038,   37.65182495,   68.08531952,
         98.51881409,  128.95230865,  159.38580322,  189.81929779,
        220.25279236,  250.68628693,  281.11978149]))
(array([    23720, 199448869,     20222,     17016,     15333,     15023,
           18014,     33247,   2359486,      7470]), array([ -67.14089203,  -27.08612595,   12.96864014,   53.02340622,
         93.0781723 ,  133.13293839,  173.18770447,  213.24247055,
        253.29723663,  293.35200272,  333.4067688 ]))
------------------------------
Creating and compiling model...
------------------------------
train.py:67: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv1 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(inputs)
train.py:68: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv1 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(conv1)
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    train_and_predict()
  File "train.py", line 157, in train_and_predict
    model = get_unet()
  File "train.py", line 69, in get_unet
    pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/keras/layers/pooling.py", line 154, in call
    data_format=self.data_format)
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/keras/layers/pooling.py", line 217, in _pooling_function
    pool_mode='max')
  File "/home/gopi/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3386, in pool2d
    x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1769, in max_pool
    name=name)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1605, in _max_pool
    data_format=data_format, name=name)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/gopi/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_1/MaxPool' (op: 'MaxPool') with input shapes: [?,1,160,32].
```

<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by ethanhe42** [comment] 2017-09-18 14:00
Duplicate of #1   
the input shape before maxpooling `[?,1,160,32]` seems weird, which should be Nx32x160x224 instead. It might caused by : 
- Keras 2, since this code hasn't been tested on it. 
- The data generated is not correct, can you verify its dimention?

**Comment by lowkeygit** [comment] 2017-09-21 17:49
I have the same problem but solve it by adding dim_ordering.
E.g.
MaxPooling2D(pool_size=(2, 2), dim_ordering="th")

Reference:
https://github.com/fchollet/keras/issues/3945

**Closed as completed** 2017-09-21 18:24 UTC
